# Copyright (c) 2025 LALO AI LLC. All rights reserved.

FROM python:3.11-slim

WORKDIR /app

COPY ../../../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "mock_workday:app", "--host", "0.0.0.0", "--port", "8202"]
