name: Qdrant Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  qdrant-integration:
    runs-on: ubuntu-latest
    services:
      qdrant:
        image: qdrant/qdrant:latest
        ports:
          - 6333:6333
        options: >-
          --health-cmd="curl -sS --fail http://localhost:6333/collections || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=12

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-ml.txt || true

      - name: Wait for Qdrant
        run: |
          echo "Waiting for Qdrant to be healthy..."
          for i in {1..30}; do
            if curl -sS --fail http://localhost:6333/collections; then
              echo "Qdrant ready"; break
            fi
            sleep 2
          done

      - name: Run Qdrant integration tests
        env:
          RUN_QDRANT_INTEGRATION: '1'
          QDRANT_URL: 'http://localhost:6333'
        run: |
          python -m pytest tests/test_qdrant_integration.py -q
